/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.emf.refactor.examples.validation;

import org.eclipse.emf.refactor.examples.validation.AbstractSimpleWebModelingLanguageValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class SimpleWebModelingLanguageValidator extends AbstractSimpleWebModelingLanguageValidator {
}
