/*
 * generated by Xtext 2.9.1
 */
package org.eclipse.emf.refactor.examples.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import org.antlr.runtime.RecognitionException;
import org.eclipse.emf.refactor.examples.ide.contentassist.antlr.internal.InternalSimpleWebModelingLanguageParser;
import org.eclipse.emf.refactor.examples.services.SimpleWebModelingLanguageGrammarAccess;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

public class SimpleWebModelingLanguageParser extends AbstractContentAssistParser {

	@Inject
	private SimpleWebModelingLanguageGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalSimpleWebModelingLanguageParser createParser() {
		InternalSimpleWebModelingLanguageParser result = new InternalSimpleWebModelingLanguageParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getPageAccess().getAlternatives(), "rule__Page__Alternatives");
					put(grammarAccess.getDynamicPageAccess().getAlternatives(), "rule__DynamicPage__Alternatives");
					put(grammarAccess.getSimpleTypeAccess().getAlternatives(), "rule__SimpleType__Alternatives");
					put(grammarAccess.getWebModelAccess().getGroup(), "rule__WebModel__Group__0");
					put(grammarAccess.getDataLayerAccess().getGroup(), "rule__DataLayer__Group__0");
					put(grammarAccess.getEntityAccess().getGroup(), "rule__Entity__Group__0");
					put(grammarAccess.getAttributeAccess().getGroup(), "rule__Attribute__Group__0");
					put(grammarAccess.getReferenceAccess().getGroup(), "rule__Reference__Group__0");
					put(grammarAccess.getHypertextLayerAccess().getGroup(), "rule__HypertextLayer__Group__0");
					put(grammarAccess.getStaticPageAccess().getGroup(), "rule__StaticPage__Group__0");
					put(grammarAccess.getLinkAccess().getGroup(), "rule__Link__Group__0");
					put(grammarAccess.getIndexPageAccess().getGroup(), "rule__IndexPage__Group__0");
					put(grammarAccess.getIndexPageAccess().getGroup_2(), "rule__IndexPage__Group_2__0");
					put(grammarAccess.getDataPageAccess().getGroup(), "rule__DataPage__Group__0");
					put(grammarAccess.getDataPageAccess().getGroup_2(), "rule__DataPage__Group_2__0");
					put(grammarAccess.getWebModelAccess().getNameAssignment_1(), "rule__WebModel__NameAssignment_1");
					put(grammarAccess.getWebModelAccess().getDataLayerAssignment_3(), "rule__WebModel__DataLayerAssignment_3");
					put(grammarAccess.getWebModelAccess().getHypertextLayerAssignment_4(), "rule__WebModel__HypertextLayerAssignment_4");
					put(grammarAccess.getDataLayerAccess().getEntitiesAssignment_2(), "rule__DataLayer__EntitiesAssignment_2");
					put(grammarAccess.getEntityAccess().getNameAssignment_1(), "rule__Entity__NameAssignment_1");
					put(grammarAccess.getEntityAccess().getAttributesAssignment_3(), "rule__Entity__AttributesAssignment_3");
					put(grammarAccess.getEntityAccess().getReferencesAssignment_4(), "rule__Entity__ReferencesAssignment_4");
					put(grammarAccess.getAttributeAccess().getNameAssignment_1(), "rule__Attribute__NameAssignment_1");
					put(grammarAccess.getAttributeAccess().getTypeAssignment_3(), "rule__Attribute__TypeAssignment_3");
					put(grammarAccess.getReferenceAccess().getNameAssignment_1(), "rule__Reference__NameAssignment_1");
					put(grammarAccess.getReferenceAccess().getTypeAssignment_3(), "rule__Reference__TypeAssignment_3");
					put(grammarAccess.getHypertextLayerAccess().getPagesAssignment_1(), "rule__HypertextLayer__PagesAssignment_1");
					put(grammarAccess.getHypertextLayerAccess().getStartPageAssignment_3(), "rule__HypertextLayer__StartPageAssignment_3");
					put(grammarAccess.getStaticPageAccess().getNameAssignment_1(), "rule__StaticPage__NameAssignment_1");
					put(grammarAccess.getStaticPageAccess().getLinksAssignment_3(), "rule__StaticPage__LinksAssignment_3");
					put(grammarAccess.getLinkAccess().getTargetAssignment_1(), "rule__Link__TargetAssignment_1");
					put(grammarAccess.getIndexPageAccess().getNameAssignment_1(), "rule__IndexPage__NameAssignment_1");
					put(grammarAccess.getIndexPageAccess().getEntityAssignment_2_1(), "rule__IndexPage__EntityAssignment_2_1");
					put(grammarAccess.getIndexPageAccess().getLinksAssignment_4(), "rule__IndexPage__LinksAssignment_4");
					put(grammarAccess.getDataPageAccess().getNameAssignment_1(), "rule__DataPage__NameAssignment_1");
					put(grammarAccess.getDataPageAccess().getEntityAssignment_2_1(), "rule__DataPage__EntityAssignment_2_1");
					put(grammarAccess.getDataPageAccess().getLinksAssignment_4(), "rule__DataPage__LinksAssignment_4");
				}
			};
		}
		return nameMappings.get(element);
	}

	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			InternalSimpleWebModelingLanguageParser typedParser = (InternalSimpleWebModelingLanguageParser) parser;
			typedParser.entryRuleWebModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public SimpleWebModelingLanguageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SimpleWebModelingLanguageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
