<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="configuration" nsURI="http://www.sidiff.org/slicing/configuration/0.1"
    nsPrefix="configuration">
  <eClassifiers xsi:type="ecore:EClass" name="SlicingConfiguration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="documentTypes" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EPackage"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="slicingMode" lowerBound="1"
        eType="#//SlicingMode" defaultValueLiteral="OPTIMISTIC"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="slicedEClasses" upperBound="-1"
        eType="#//SlicedEClass" containment="true" eOpposite="#//SlicedEClass/slicingConfiguration"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="oppositeSlicedEClassType"
        changeable="false" volatile="true" transient="true" derived="true">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
        <eTypeArguments/>
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//Constraint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraintinterpreter"
        eType="#//IConstraintInterpreter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SlicingMode">
    <eLiterals name="OPTIMISTIC"/>
    <eLiterals name="PESSIMISTIC" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SlicedEClass">
    <eStructuralFeatures xsi:type="ecore:EReference" name="slicingConfiguration" lowerBound="1"
        eType="#//SlicingConfiguration" eOpposite="#//SlicingConfiguration/slicedEClasses"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//Constraint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IConstraintInterpreter" abstract="true"
      interface="true">
    <eOperations name="evaluate" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean">
      <eParameters name="constraint" eType="#//Constraint"/>
      <eParameters name="context" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    </eOperations>
    <eOperations name="evaluate" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean">
      <eParameters name="constraints">
        <eGenericType eClassifier="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EEList">
          <eTypeArguments eClassifier="#//Constraint"/>
        </eGenericType>
      </eParameters>
      <eParameters name="context" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        changeable="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OCLConstraintInterpreter" eSuperTypes="#//IConstraintInterpreter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ocl" lowerBound="1" eType="#//EOCL"
        changeable="false" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="oclHelper" lowerBound="1"
        eType="#//EOCLHelper" changeable="false" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EOCL" instanceClassName="org.eclipse.ocl.ecore.OCL"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EOCLHelper" instanceClassName="org.eclipse.ocl.helper.OCLHelper"/>
</ecore:EPackage>
