/**
 */
package de.imotep.core.datamodel.de_imotep_core_datamodel.provider;

import de.imotep.core.datamodel.de_imotep_core_datamodel.util.De_imotep_core_datamodelAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class De_imotep_core_datamodelItemProviderAdapterFactory extends De_imotep_core_datamodelAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public De_imotep_core_datamodelItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.imotep.core.datamodel.de_imotep_core_datamodel.MNamedEntity} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MNamedEntityItemProvider mNamedEntityItemProvider;

	/**
	 * This creates an adapter for a {@link de.imotep.core.datamodel.de_imotep_core_datamodel.MNamedEntity}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMNamedEntityAdapter() {
		if (mNamedEntityItemProvider == null) {
			mNamedEntityItemProvider = new MNamedEntityItemProvider(this);
		}

		return mNamedEntityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.imotep.core.datamodel.de_imotep_core_datamodel.MIntegerAttribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MIntegerAttributeItemProvider mIntegerAttributeItemProvider;

	/**
	 * This creates an adapter for a {@link de.imotep.core.datamodel.de_imotep_core_datamodel.MIntegerAttribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMIntegerAttributeAdapter() {
		if (mIntegerAttributeItemProvider == null) {
			mIntegerAttributeItemProvider = new MIntegerAttributeItemProvider(this);
		}

		return mIntegerAttributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.imotep.core.datamodel.de_imotep_core_datamodel.MStringAttribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MStringAttributeItemProvider mStringAttributeItemProvider;

	/**
	 * This creates an adapter for a {@link de.imotep.core.datamodel.de_imotep_core_datamodel.MStringAttribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMStringAttributeAdapter() {
		if (mStringAttributeItemProvider == null) {
			mStringAttributeItemProvider = new MStringAttributeItemProvider(this);
		}

		return mStringAttributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.imotep.core.datamodel.de_imotep_core_datamodel.MEntity} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MEntityItemProvider mEntityItemProvider;

	/**
	 * This creates an adapter for a {@link de.imotep.core.datamodel.de_imotep_core_datamodel.MEntity}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMEntityAdapter() {
		if (mEntityItemProvider == null) {
			mEntityItemProvider = new MEntityItemProvider(this);
		}

		return mEntityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.imotep.core.datamodel.de_imotep_core_datamodel.MRangedIntegerAttribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MRangedIntegerAttributeItemProvider mRangedIntegerAttributeItemProvider;

	/**
	 * This creates an adapter for a {@link de.imotep.core.datamodel.de_imotep_core_datamodel.MRangedIntegerAttribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMRangedIntegerAttributeAdapter() {
		if (mRangedIntegerAttributeItemProvider == null) {
			mRangedIntegerAttributeItemProvider = new MRangedIntegerAttributeItemProvider(this);
		}

		return mRangedIntegerAttributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.imotep.core.datamodel.de_imotep_core_datamodel.MBooleanAttribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MBooleanAttributeItemProvider mBooleanAttributeItemProvider;

	/**
	 * This creates an adapter for a {@link de.imotep.core.datamodel.de_imotep_core_datamodel.MBooleanAttribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMBooleanAttributeAdapter() {
		if (mBooleanAttributeItemProvider == null) {
			mBooleanAttributeItemProvider = new MBooleanAttributeItemProvider(this);
		}

		return mBooleanAttributeItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (mNamedEntityItemProvider != null) mNamedEntityItemProvider.dispose();
		if (mIntegerAttributeItemProvider != null) mIntegerAttributeItemProvider.dispose();
		if (mStringAttributeItemProvider != null) mStringAttributeItemProvider.dispose();
		if (mEntityItemProvider != null) mEntityItemProvider.dispose();
		if (mRangedIntegerAttributeItemProvider != null) mRangedIntegerAttributeItemProvider.dispose();
		if (mBooleanAttributeItemProvider != null) mBooleanAttributeItemProvider.dispose();
	}

}
