/*
 * generated by Xtext
 */
package org.eclipse.emf.refactor.examples.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SimpleWebModelingLanguageUiModule extends org.eclipse.emf.refactor.examples.ui.AbstractSimpleWebModelingLanguageUiModule {
	public SimpleWebModelingLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
