/*
 * generated by Xtext
 */
package org.eclipse.emf.refactor.examples.ui.contentassist

import org.eclipse.emf.refactor.examples.ui.contentassist.AbstractSimpleWebModelingLanguageProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class SimpleWebModelingLanguageProposalProvider extends AbstractSimpleWebModelingLanguageProposalProvider {
}
