package org.sidiff.editrule.consistency.validation;

public enum ValidationType {
	ruleOrganization,
	mainUnit,
	mainUnitType,
	mainUnitComposition,
	noUnusedParameters,
	uniqueParameterNames,
	mappedAllRuleObjectInParameters,
	mappedAllCreateNodes,
	mappedAllValueSettingParameters,
	correctParameterTyping,
	consistentEOpposite, 
	derivedEdges,
	atLeastOneAction,
	acComposition,
	acBoundaries,
	lhsBoundaries,
	noAcBoundaryAttributes, 
	multiRuleNodeEmbedding,
	multiRuleEdgeEmbedding,
	multiRuleAttributeEmbedding,
	multiRuleParameterEmbedding,
	uniqueMultiMappings,
	knownAnnotation, 
	wrongParameterKind_IN_expected, 
	wrongParameterKind_UNKNOWN_expected, 
	wrongParameterKind_OUT_expected
}
