/*
 * generated by Xtext
 */
package org.eclipse.emf.refactor.examples.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.emf.refactor.examples.services.SimpleWebModelingLanguageGrammarAccess;

public class SimpleWebModelingLanguageParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SimpleWebModelingLanguageGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.eclipse.emf.refactor.examples.parser.antlr.internal.InternalSimpleWebModelingLanguageParser createParser(XtextTokenStream stream) {
		return new org.eclipse.emf.refactor.examples.parser.antlr.internal.InternalSimpleWebModelingLanguageParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "WebModel";
	}
	
	public SimpleWebModelingLanguageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SimpleWebModelingLanguageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
