/*
 * generated by Xtext 2.10.0
 */
package org.eclipse.emf.refactor.examples


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SimpleWebModelingLanguageStandaloneSetup extends SimpleWebModelingLanguageStandaloneSetupGenerated {

	def static void doSetup() {
		new SimpleWebModelingLanguageStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
