<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="symboliclink" nsURI="http://symboliclink/1.0" nsPrefix="symboliclink">
  <eClassifiers xsi:type="ecore:EClass" name="SymbolicLinks">
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkObjects" upperBound="-1"
        eType="#//SymbolicLinkObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="docType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkReferences" upperBound="-1"
        eType="#//SymbolicLinkReference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SymbolicLinkObject" abstract="true">
    <eOperations name="getOutgoings">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
        <eTypeArguments/>
      </eGenericType>
      <eParameters name="type" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EReference"/>
    </eOperations>
    <eOperations name="hashCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reliability" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" upperBound="-1"
        eType="#//SymbolicLinkReference" eOpposite="#//SymbolicLinkReference/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" upperBound="-1"
        eType="#//SymbolicLinkReference" eOpposite="#//SymbolicLinkReference/target"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SymbolicLinkReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//SymbolicLinkObject" eOpposite="#//SymbolicLinkObject/outgoing"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//SymbolicLinkObject" eOpposite="#//SymbolicLinkObject/incoming"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalSymbolicLinkObject" eSuperTypes="#//SymbolicLinkObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eObject" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="from" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        volatile="true" transient="true" derived="true"/>
  </eClassifiers>
</ecore:EPackage>
