/**
 *
 * $Id$
 */
package org.eclipse.emf.henshin.model.validation;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.henshin.model.Node;
import org.eclipse.emf.henshin.model.Rule;
import org.eclipse.emf.henshin.model.Unit;


/**
 * A sample validator interface for {@link org.eclipse.emf.henshin.model.Join}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface JoinValidator {
	boolean validate();

	boolean validateRule(Unit value);

	boolean validateRule(Rule value);

	boolean validateJoinFrom(EList<Node> value);

	boolean validateJoinInto(EList<Node> value);

	boolean validateJoinInto(Node value);

}
