/**
 *
 * $Id$
 */
package org.eclipse.emf.henshin.model.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.henshin.model.Join;
import org.eclipse.emf.henshin.model.Parameter;
import org.eclipse.emf.henshin.model.ParameterMapping;
import org.eclipse.emf.henshin.model.Split;

/**
 * A sample validator interface for {@link org.eclipse.emf.henshin.model.Unit}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface UnitValidator {
	boolean validate();

	boolean validateParameters(EList<Parameter> value);
	boolean validateParameterMappings(EList<ParameterMapping> value);
	boolean validateActivated(boolean value);

	boolean validateJoins(EList<Join> value);

	boolean validateSplits(EList<Split> value);
}
