/*
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package org.eclipse.emf.refactor.examples.ide

import com.google.inject.Guice
import org.eclipse.emf.refactor.examples.SimpleWebModelingLanguageRuntimeModule
import org.eclipse.emf.refactor.examples.SimpleWebModelingLanguageStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class SimpleWebModelingLanguageIdeSetup extends SimpleWebModelingLanguageStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new SimpleWebModelingLanguageRuntimeModule, new SimpleWebModelingLanguageIdeModule))
	}
	
}
