/*
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package org.eclipse.emf.refactor.examples.ide


/**
 * Use this class to register ide components.
 */
class SimpleWebModelingLanguageIdeModule extends AbstractSimpleWebModelingLanguageIdeModule {
}
