/*
 * generated by Xtext
 */
package org.eclipse.emf.refactor.examples;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SimpleWebModelingLanguageUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.eclipse.emf.refactor.examples.ui.internal.SimpleWebModelingLanguageActivator.getInstance().getInjector("org.eclipse.emf.refactor.examples.SimpleWebModelingLanguage");
	}
	
}
