<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="slice" nsURI="http://www.example.org/Slice" nsPrefix="Slice">
  <eClassifiers xsi:type="ecore:EClass" name="ModelSlice">
    <eStructuralFeatures xsi:type="ecore:EReference" name="slicedElements" upperBound="-1"
        eType="#//SlicedElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EPackage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SlicedElement" eSuperTypes="../../org.sidiff.entities/model/EntitiesModel.ecore#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="slicedReferences" upperBound="-1"
        eType="ecore:EClass ../../org.sidiff.entities/model/EntitiesModel.ecore#//Reference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="slicedAttributes" upperBound="-1"
        eType="ecore:EClass ../../org.sidiff.entities/model/EntitiesModel.ecore#//Attribute"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
