<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="slice" nsURI="http://www.sidiff.org/slice/model/1.0" nsPrefix="slice">
  <eClassifiers xsi:type="ecore:EClass" name="ModelSlice">
    <eOperations name="export" upperBound="-1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Returns a collection of all containers that properly contain all sliced objects.&#xD;&#xA;If the given resource is not null, all objects contained in this resource will be copied.&#xD;&#xA;If the resource is null, all objects will be copied."/>
      </eAnnotations>
      <eParameters name="sourceResource" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EResource"/>
    </eOperations>
    <eOperations name="serialize">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="ResourceSet resourceSet = new ResourceSetImpl();  Resource resource = resourceSet.createResource(EMFStorage.pathToUri(path)); resource.getContents().add(this);  try { resource.save(null); } catch (IOException e) {e.printStackTrace(); }"/>
      </eAnnotations>
      <eParameters name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="slicedElements" upperBound="-1"
        eType="#//SlicedElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EPackage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SlicedElement" eSuperTypes="../../org.sidiff.entities/model/EntitiesModel.ecore#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="slicedReferences" upperBound="-1"
        eType="ecore:EClass ../../org.sidiff.entities/model/EntitiesModel.ecore#//Reference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="slicedAttributes" upperBound="-1"
        eType="ecore:EClass ../../org.sidiff.entities/model/EntitiesModel.ecore#//Attribute"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
