/*
 * generated by Xtext
 */
package org.eclipse.emf.refactor.examples;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SimpleWebModelingLanguageRuntimeModule extends org.eclipse.emf.refactor.examples.AbstractSimpleWebModelingLanguageRuntimeModule {

}
