/*
 * generated by Xtext
 */
package org.eclipse.emf.refactor.examples;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SimpleWebModelingLanguageStandaloneSetup extends SimpleWebModelingLanguageStandaloneSetupGenerated{

	public static void doSetup() {
		new SimpleWebModelingLanguageStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

