<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="de_imotep_core_datamodel" nsURI="http://www.moflon.org.de_imotep_core_datamodel"
    nsPrefix="de_imotep_core_datamodel">
  <eClassifiers xsi:type="ecore:EDataType" name="JObject" instanceTypeName="Object"/>
  <eClassifiers xsi:type="ecore:EDataType" name="JCollection" instanceTypeName="Collection"/>
  <eClassifiers xsi:type="ecore:EEnum" name="MEVisibility">
    <eLiterals name="PUBLIC"/>
    <eLiterals name="PRIVATE" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MAttribute" abstract="true" eSuperTypes="#//MNamedEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isStatic" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" ordered="false"
        lowerBound="1" eType="#//MEVisibility"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MNamedEntity" eSuperTypes="#//MEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MIntegerAttribute" eSuperTypes="#//MAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initValue" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MStringAttribute" eSuperTypes="#//MAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initValue" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MRangedIntegerAttribute" eSuperTypes="#//MIntegerAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximum" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minimum" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="JList" instanceTypeName="List"/>
  <eClassifiers xsi:type="ecore:EClass" name="MBooleanAttribute" eSuperTypes="#//MAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initValue" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="JSet" instanceTypeName="Set"/>
</ecore:EPackage>
