/**
 * generated by Xtext 2.9.1
 */
package org.eclipse.emf.refactor.examples.simpleWebModelingLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Data Page</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.eclipse.emf.refactor.examples.simpleWebModelingLanguage.SimpleWebModelingLanguagePackage#getDataPage()
 * @model
 * @generated
 */
public interface DataPage extends DynamicPage
{
} // DataPage
