<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="uml" nsURI="http://www.eclipse.org/uml2/5.0.0/UML" nsPrefix="uml">
  <eClassifiers xsi:type="ecore:EClass" name="Activity" eSuperTypes="#//Behavior">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedGroup" ordered="false"
        upperBound="-1" eType="#//ActivityGroup" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edge" ordered="false" upperBound="-1"
        eType="#//ActivityEdge" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="node" ordered="false" upperBound="-1"
        eType="#//ActivityNode" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" ordered="false"
        upperBound="-1" eType="#//Variable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="group" ordered="false"
        upperBound="-1" eType="#//ActivityGroup" volatile="true" transient="true"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedNode" ordered="false"
        upperBound="-1" eType="#//ActivityNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isReadOnly" ordered="false"
        lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//Boolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isSingleExecution" ordered="false"
        lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//Boolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="partition" ordered="false"
        upperBound="-1" eType="#//ActivityPartition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="structuredNode" ordered="false"
        upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//StructuredActivityNode"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Behavior" abstract="true" eSuperTypes="#//Class">
    <eStructuralFeatures xsi:type="ecore:EReference" name="specification" ordered="false"
        eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//BehavioralFeature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" ordered="false"
        eType="#//BehavioredClassifier" changeable="false" volatile="true" transient="true"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isReentrant" ordered="false"
        eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//Boolean"
        defaultValueLiteral="true" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedParameter" upperBound="-1"
        eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Parameter"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedParameterSet" ordered="false"
        upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//ParameterSet"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="postcondition" ordered="false"
        upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Constraint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="precondition" ordered="false"
        upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Constraint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="redefinedBehavior" ordered="false"
        upperBound="-1" eType="#//Behavior"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Class" eSuperTypes="#//EncapsulatedClassifier #//BehavioredClassifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedOperation" upperBound="-1"
        eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Operation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extension" ordered="false"
        upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Extension"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isActive" ordered="false"
        lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//Boolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nestedClassifier" upperBound="-1"
        eType="#//Classifier" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedReception" ordered="false"
        upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Reception"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superClass" ordered="false"
        upperBound="-1" eType="#//Class" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BehavioredClassifier" abstract="true"
      eSuperTypes="#//Classifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classifierBehavior" ordered="false"
        eType="#//Behavior"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interfaceRealization" ordered="false"
        upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//InterfaceRealization"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedBehavior" ordered="false"
        upperBound="-1" eType="#//Behavior" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Classifier" abstract="true" eSuperTypes="#//Namespace #//RedefinableElement #//Type #//TemplateableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" ordered="false"
        upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Feature"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" upperBound="-1"
        eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="collaborationUse" ordered="false"
        upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//CollaborationUse"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="general" ordered="false"
        upperBound="-1" eType="#//Classifier" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generalization" ordered="false"
        upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Generalization"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="powertypeExtent" ordered="false"
        upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//GeneralizationSet"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inheritedMember" ordered="false"
        upperBound="-1" eType="#//NamedElement" changeable="false" volatile="true"
        transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAbstract" ordered="false"
        lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//Boolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isFinalSpecialization"
        ordered="false" lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//Boolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedUseCase" ordered="false"
        upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//UseCase"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="useCase" ordered="false"
        upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//UseCase"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="redefinedClassifier" ordered="false"
        upperBound="-1" eType="#//Classifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="representation" ordered="false"
        eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//CollaborationUse"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="substitution" ordered="false"
        upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Substitution"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Namespace" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedRule" ordered="false"
        upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Constraint"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementImport" ordered="false"
        upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//ElementImport"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="packageImport" ordered="false"
        upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//PackageImport"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedMember" ordered="false"
        upperBound="-1" eType="#//NamedElement" changeable="false" volatile="true"
        transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="importedMember" ordered="false"
        upperBound="-1" eType="#//PackageableElement" changeable="false" volatile="true"
        transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="member" ordered="false"
        upperBound="-1" eType="#//NamedElement" changeable="false" volatile="true"
        transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="clientDependency" ordered="false"
        upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Dependency"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//String"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nameExpression" ordered="false"
        eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//StringExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="namespace" ordered="false"
        eType="#//Namespace" changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifiedName" ordered="false"
        eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//String"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" ordered="false"
        eType="#//VisibilityKind" unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedComment" ordered="false"
        upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Comment"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedElement" ordered="false"
        upperBound="-1" eType="#//Element" changeable="false" volatile="true" transient="true"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" ordered="false"
        eType="#//Element" changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PackageableElement" abstract="true"
      eSuperTypes="#//NamedElement #//ParameterableElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterableElement" abstract="true"
      eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningTemplateParameter"
        ordered="false" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//TemplateParameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="templateParameter" ordered="false"
        eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//TemplateParameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TemplateableElement" abstract="true"
      eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="templateBinding" ordered="false"
        upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//TemplateBinding"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedTemplateSignature"
        ordered="false" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//TemplateSignature"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VisibilityKind">
    <eLiterals name="public"/>
    <eLiterals name="private" value="1"/>
    <eLiterals name="protected" value="2"/>
    <eLiterals name="package" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true" eSuperTypes="#//PackageableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="package" ordered="false"
        eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Package"
        volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectableElement" abstract="true"
      eSuperTypes="#//TypedElement #//ParameterableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" ordered="false" upperBound="-1"
        eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//ConnectorEnd"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypedElement" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" eType="#//Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MultiplicityElement" abstract="true"
      eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isOrdered" ordered="false"
        lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//Boolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isUnique" ordered="false"
        lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//Boolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lower" ordered="false"
        eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//Integer"
        volatile="true" transient="true" defaultValueLiteral="1" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lowerValue" ordered="false"
        eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//ValueSpecification"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upper" ordered="false"
        lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//UnlimitedNatural"
        volatile="true" transient="true" defaultValueLiteral="1" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="upperValue" ordered="false"
        eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//ValueSpecification"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ParameterDirectionKind">
    <eLiterals name="in"/>
    <eLiterals name="inout" value="1"/>
    <eLiterals name="out" value="2"/>
    <eLiterals name="return" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ParameterEffectKind">
    <eLiterals name="create"/>
    <eLiterals name="read" value="1"/>
    <eLiterals name="update" value="2"/>
    <eLiterals name="delete" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RedefinableElement" abstract="true"
      eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isLeaf" ordered="false"
        lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//Boolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="redefinedElement" ordered="false"
        upperBound="-1" eType="#//RedefinableElement" changeable="false" volatile="true"
        transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="redefinitionContext" ordered="false"
        upperBound="-1" eType="#//Classifier" changeable="false" volatile="true" transient="true"
        derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CallConcurrencyKind">
    <eLiterals name="sequential"/>
    <eLiterals name="guarded" value="1"/>
    <eLiterals name="concurrent" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TransitionKind">
    <eLiterals name="internal"/>
    <eLiterals name="local" value="1"/>
    <eLiterals name="external" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PseudostateKind">
    <eLiterals name="initial"/>
    <eLiterals name="deepHistory" value="1"/>
    <eLiterals name="shallowHistory" value="2"/>
    <eLiterals name="join" value="3"/>
    <eLiterals name="fork" value="4"/>
    <eLiterals name="junction" value="5"/>
    <eLiterals name="choice" value="6"/>
    <eLiterals name="entryPoint" value="7"/>
    <eLiterals name="exitPoint" value="8"/>
    <eLiterals name="terminate" value="9"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AggregationKind">
    <eLiterals name="none"/>
    <eLiterals name="shared" value="1"/>
    <eLiterals name="composite" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StructuredClassifier" abstract="true"
      eSuperTypes="#//Classifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedAttribute" upperBound="-1"
        eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedConnector" ordered="false"
        upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Connector"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="part" ordered="false" upperBound="-1"
        eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="role" ordered="false" upperBound="-1"
        eType="#//ConnectableElement" changeable="false" volatile="true" transient="true"
        derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ConnectorKind">
    <eLiterals name="assembly"/>
    <eLiterals name="delegation" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EncapsulatedClassifier" abstract="true"
      eSuperTypes="#//StructuredClassifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPort" ordered="false"
        upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Port"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityGroup" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedEdge" ordered="false"
        upperBound="-1" eType="#//ActivityEdge" changeable="false" volatile="true"
        transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedNode" ordered="false"
        upperBound="-1" eType="#//ActivityNode" changeable="false" volatile="true"
        transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inActivity" ordered="false"
        eType="#//Activity" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subgroup" ordered="false"
        upperBound="-1" eType="#//ActivityGroup" changeable="false" volatile="true"
        transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superGroup" ordered="false"
        eType="#//ActivityGroup" changeable="false" volatile="true" transient="true"
        derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityEdge" abstract="true" eSuperTypes="#//RedefinableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activity" ordered="false"
        eType="#//Activity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guard" ordered="false"
        eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//ValueSpecification"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inPartition" ordered="false"
        upperBound="-1" eType="#//ActivityPartition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interrupts" ordered="false"
        eType="#//InterruptibleActivityRegion"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inStructuredNode" ordered="false"
        eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//StructuredActivityNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" ordered="false"
        lowerBound="1" eType="#//ActivityNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false"
        lowerBound="1" eType="#//ActivityNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="redefinedEdge" ordered="false"
        upperBound="-1" eType="#//ActivityEdge"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="weight" ordered="false"
        eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//ValueSpecification"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inGroup" ordered="false"
        upperBound="-1" eType="#//ActivityGroup" changeable="false" volatile="true"
        transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityPartition" eSuperTypes="#//ActivityGroup">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDimension" ordered="false"
        lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//Boolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isExternal" ordered="false"
        lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//Boolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="node" ordered="false" upperBound="-1"
        eType="#//ActivityNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="represents" ordered="false"
        eType="#//Element"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subpartition" ordered="false"
        upperBound="-1" eType="#//ActivityPartition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superPartition" ordered="false"
        eType="#//ActivityPartition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edge" ordered="false" upperBound="-1"
        eType="#//ActivityEdge"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityNode" abstract="true" eSuperTypes="#//RedefinableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activity" ordered="false"
        eType="#//Activity" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inGroup" ordered="false"
        upperBound="-1" eType="#//ActivityGroup" changeable="false" volatile="true"
        transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inInterruptibleRegion"
        ordered="false" upperBound="-1" eType="#//InterruptibleActivityRegion"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inStructuredNode" ordered="false"
        eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//StructuredActivityNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" ordered="false"
        upperBound="-1" eType="#//ActivityEdge"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" ordered="false"
        upperBound="-1" eType="#//ActivityEdge"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="redefinedNode" ordered="false"
        upperBound="-1" eType="#//ActivityNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inPartition" ordered="false"
        upperBound="-1" eType="#//ActivityPartition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InterruptibleActivityRegion" eSuperTypes="#//ActivityGroup">
    <eStructuralFeatures xsi:type="ecore:EReference" name="interruptingEdge" ordered="false"
        upperBound="-1" eType="#//ActivityEdge"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="node" ordered="false" upperBound="-1"
        eType="#//ActivityNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutableNode" abstract="true" eSuperTypes="#//ActivityNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="handler" ordered="false"
        upperBound="-1" eType="#//ExceptionHandler" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExceptionHandler" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="exceptionInput" ordered="false"
        lowerBound="1" eType="#//ObjectNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exceptionType" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//Classifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="handlerBody" ordered="false"
        lowerBound="1" eType="#//ExecutableNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="protectedNode" ordered="false"
        lowerBound="1" eType="#//ExecutableNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectNode" abstract="true" eSuperTypes="#//ActivityNode #//TypedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inState" ordered="false"
        upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//State"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isControlType" ordered="false"
        lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//Boolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ordering" ordered="false"
        lowerBound="1" eType="#//ObjectNodeOrderingKind" defaultValueLiteral="FIFO"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selection" ordered="false"
        eType="#//Behavior"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="upperBound" ordered="false"
        eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//ValueSpecification"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ObjectNodeOrderingKind">
    <eLiterals name="unordered"/>
    <eLiterals name="ordered" value="1"/>
    <eLiterals name="LIFO" value="2"/>
    <eLiterals name="FIFO" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="#//ConnectableElement #//MultiplicityElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activityScope" ordered="false"
        eType="#//Activity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scope" ordered="false"
        eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//StructuredActivityNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ExpansionKind">
    <eLiterals name="parallel"/>
    <eLiterals name="iterative" value="1"/>
    <eLiterals name="stream" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityFinalNode" eSuperTypes="#//FinalNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="FinalNode" abstract="true" eSuperTypes="#//ControlNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="ControlNode" abstract="true" eSuperTypes="#//ActivityNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityParameterNode" eSuperTypes="#//ObjectNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" ordered="false"
        lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Parameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CentralBufferNode" eSuperTypes="#//ObjectNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="ControlFlow" eSuperTypes="#//ActivityEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataStoreNode" eSuperTypes="#//CentralBufferNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="DecisionNode" eSuperTypes="#//ControlNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="decisionInput" ordered="false"
        eType="#//Behavior"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="decisionInputFlow" ordered="false"
        eType="#//ObjectFlow"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectFlow" eSuperTypes="#//ActivityEdge">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMulticast" ordered="false"
        lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//Boolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMultireceive" ordered="false"
        lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//Boolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selection" ordered="false"
        eType="#//Behavior"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transformation" ordered="false"
        eType="#//Behavior"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FlowFinalNode" eSuperTypes="#//FinalNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="ForkNode" eSuperTypes="#//ControlNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="InitialNode" eSuperTypes="#//ControlNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="JoinNode" eSuperTypes="#//ControlNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isCombineDuplicate" ordered="false"
        lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//Boolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="joinSpec" ordered="false"
        eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//ValueSpecification"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MergeNode" eSuperTypes="#//ControlNode"/>
  <eClassifiers xsi:type="ecore:EEnum" name="MessageKind">
    <eLiterals name="complete"/>
    <eLiterals name="lost" value="1"/>
    <eLiterals name="found" value="2"/>
    <eLiterals name="unknown" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MessageSort">
    <eLiterals name="synchCall"/>
    <eLiterals name="asynchCall" value="1"/>
    <eLiterals name="asynchSignal" value="2"/>
    <eLiterals name="createMessage" value="3"/>
    <eLiterals name="deleteMessage" value="4"/>
    <eLiterals name="reply" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="InteractionOperatorKind">
    <eLiterals name="seq"/>
    <eLiterals name="alt" value="1"/>
    <eLiterals name="opt" value="2"/>
    <eLiterals name="break" value="3"/>
    <eLiterals name="par" value="4"/>
    <eLiterals name="strict" value="5"/>
    <eLiterals name="loop" value="6"/>
    <eLiterals name="critical" value="7"/>
    <eLiterals name="neg" value="8"/>
    <eLiterals name="assert" value="9"/>
    <eLiterals name="ignore" value="10"/>
    <eLiterals name="consider" value="11"/>
  </eClassifiers>
</ecore:EPackage>
