<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model"
    nsURI="http://model/1.0" nsPrefix="model">
  <eClassifiers xsi:type="ecore:EClass" name="EClass0">
    <eOperations name="EOperation0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="EAttribute0" defaultValueLiteral=""
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="EAttribute1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="EAttribute2"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="EAttribute3" derived="true"/>
  </eClassifiers>
</ecore:EPackage>
