/*
 * generated by Xtext
 */
package org.eclipse.emf.refactor.examples.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.eclipse.emf.refactor.examples.ui.internal.SimpleWebModelingLanguageActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SimpleWebModelingLanguageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SimpleWebModelingLanguageActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SimpleWebModelingLanguageActivator.getInstance().getInjector(SimpleWebModelingLanguageActivator.ORG_ECLIPSE_EMF_REFACTOR_EXAMPLES_SIMPLEWEBMODELINGLANGUAGE);
	}
	
}
