<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmi:id="_qUHTcH0_EeC_4fSSxHu_sw"
    name="gmfgraph" nsURI="http://www.eclipse.org/gmf/2005/GraphicalDefinition" nsPrefix="gmfgraph">
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUHTcX0_EeC_4fSSxHu_sw" name="Identity"
      interface="true">
    <eAnnotations xmi:id="_qUHTcn0_EeC_4fSSxHu_sw" source="http://www.eclipse.org/emf/2002/GenModel">
      <details xmi:id="_qUHTc30_EeC_4fSSxHu_sw" key="documentation" value="Easy and readable way to reference element of the model from another one"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUHTdH0_EeC_4fSSxHu_sw"
        name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUHTdn0_EeC_4fSSxHu_sw" name="Canvas"
      eSuperTypes="#_qUHTcX0_EeC_4fSSxHu_sw">
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_qUHTd30_EeC_4fSSxHu_sw"
        name="figures" upperBound="-1" eType="#_qUHThH0_EeC_4fSSxHu_sw" containment="true">
      <eAnnotations xmi:id="_qUHTeH0_EeC_4fSSxHu_sw" source="http://www.eclipse.org/emf/2002/GenModel">
        <details xmi:id="_qUHTeX0_EeC_4fSSxHu_sw" key="documentation" value="containment here doesn't restrict nodes/connection from using figure galeries defined elsewhere. No assumption should be made whether or not node/connection figure is defined in the galery beloning to this canvas"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_qUHTe30_EeC_4fSSxHu_sw"
        name="nodes" upperBound="-1" eType="#_qUHTmn0_EeC_4fSSxHu_sw" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_qUHTfX0_EeC_4fSSxHu_sw"
        name="connections" upperBound="-1" eType="#_qUHTon0_EeC_4fSSxHu_sw" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_qUHTf30_EeC_4fSSxHu_sw"
        name="compartments" upperBound="-1" eType="#_qUHTqH0_EeC_4fSSxHu_sw" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_qUHTgX0_EeC_4fSSxHu_sw"
        name="labels" upperBound="-1" eType="#_qUHTrn0_EeC_4fSSxHu_sw" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUHThH0_EeC_4fSSxHu_sw" name="FigureGallery"
      eSuperTypes="#_qUHTcX0_EeC_4fSSxHu_sw">
    <eAnnotations xmi:id="_qUHThX0_EeC_4fSSxHu_sw" source="http://www.eclipse.org/emf/2002/GenModel">
      <details xmi:id="_qUHThn0_EeC_4fSSxHu_sw" key="documentation" value="Kind of explicit figure library notion. Bundle of figures. Allows to specify plugin id (allows importing it later from gmfgen code) in addition to figures"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUHTh30_EeC_4fSSxHu_sw"
        name="implementationBundle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_qUHTiX0_EeC_4fSSxHu_sw"
        name="figures" upperBound="-1" eType="#_qUH63n0_EeC_4fSSxHu_sw" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUHTjH0_EeC_4fSSxHu_sw" name="DiagramElement"
      abstract="true" eSuperTypes="#_qUHTcX0_EeC_4fSSxHu_sw">
    <eOperations xmi:id="_qUHTjX0_EeC_4fSSxHu_sw" name="find" eType="#_qUHTsn0_EeC_4fSSxHu_sw">
      <eAnnotations xmi:id="_qUHTjn0_EeC_4fSSxHu_sw" source="http://www.eclipse.org/emf/2002/GenModel">
        <details xmi:id="_qUHTj30_EeC_4fSSxHu_sw" key="documentation" value="utility operation to get first visual facet assignable (in Java terms, {@link Class#isAssignableFrom(Class)}) to variables of designated class. Argument can't be null"/>
      </eAnnotations>
      <eParameters xmi:id="_qUHTkX0_EeC_4fSSxHu_sw" name="facetClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_qUHTk30_EeC_4fSSxHu_sw"
        name="facets" upperBound="-1" eType="#_qUHTsn0_EeC_4fSSxHu_sw" containment="true">
      <eAnnotations xmi:id="_qUHTlH0_EeC_4fSSxHu_sw" source="http://www.eclipse.org/emf/2002/GenModel">
        <details xmi:id="_qUHTlX0_EeC_4fSSxHu_sw" key="documentation" value="anything to further specify constraint or any other aspect of the element"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_qUHTl30_EeC_4fSSxHu_sw"
        name="figure" lowerBound="1" eType="#_qUHTy30_EeC_4fSSxHu_sw" eOpposite="#_qUHTzn0_EeC_4fSSxHu_sw"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUHTmn0_EeC_4fSSxHu_sw" name="Node"
      eSuperTypes="#_qUHTjH0_EeC_4fSSxHu_sw">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUHTm30_EeC_4fSSxHu_sw"
        name="resizeConstraint" eType="#_qUH6mH0_EeC_4fSSxHu_sw" defaultValueLiteral="NSEW"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_qUHTnX0_EeC_4fSSxHu_sw"
        name="nodeFigure" lowerBound="1" eType="#_qUH63n0_EeC_4fSSxHu_sw" changeable="false"
        volatile="true" transient="true" derived="true" resolveProxies="false">
      <eAnnotations xmi:id="_qUHTnn0_EeC_4fSSxHu_sw" source="http://www.eclipse.org/emf/2002/GenModel">
        <details xmi:id="_qUHTn30_EeC_4fSSxHu_sw" key="documentation" value="Specializes DiagramElement.figure"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUHTon0_EeC_4fSSxHu_sw" name="Connection"
      eSuperTypes="#_qUHTjH0_EeC_4fSSxHu_sw">
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_qUHTo30_EeC_4fSSxHu_sw"
        name="connectionFigure" lowerBound="1" eType="#_qUH63n0_EeC_4fSSxHu_sw" changeable="false"
        volatile="true" transient="true" derived="true" resolveProxies="false">
      <eAnnotations xmi:id="_qUHTpH0_EeC_4fSSxHu_sw" source="http://www.eclipse.org/emf/2002/GenModel">
        <details xmi:id="_qUHTpX0_EeC_4fSSxHu_sw" key="documentation" value="Specializes DiagramElement.figure"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUHTqH0_EeC_4fSSxHu_sw" name="Compartment"
      eSuperTypes="#_qUHTjH0_EeC_4fSSxHu_sw">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUHTqX0_EeC_4fSSxHu_sw"
        name="collapsible" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUHTq30_EeC_4fSSxHu_sw"
        name="needsTitle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUHTrn0_EeC_4fSSxHu_sw" name="DiagramLabel"
      eSuperTypes="#_qUHTmn0_EeC_4fSSxHu_sw">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUHTr30_EeC_4fSSxHu_sw"
        name="elementIcon" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUHTsn0_EeC_4fSSxHu_sw" name="VisualFacet"
      interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUHTs30_EeC_4fSSxHu_sw" name="GeneralFacet"
      eSuperTypes="#_qUHTsn0_EeC_4fSSxHu_sw">
    <eAnnotations xmi:id="_qUHTtH0_EeC_4fSSxHu_sw" source="http://www.eclipse.org/emf/2002/GenModel">
      <details xmi:id="_qUHTtX0_EeC_4fSSxHu_sw" key="documentation" value="provide means to attach arbitrary data to your diagram element definition. It's up to you (template author) to process it somehow."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUHTtn0_EeC_4fSSxHu_sw"
        name="identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUHTuH0_EeC_4fSSxHu_sw"
        name="data" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUHTu30_EeC_4fSSxHu_sw" name="AlignmentFacet"
      eSuperTypes="#_qUHTsn0_EeC_4fSSxHu_sw">
    <eAnnotations xmi:id="_qUHTvH0_EeC_4fSSxHu_sw" source="http://www.eclipse.org/emf/2002/GenModel">
      <details xmi:id="_qUHTvX0_EeC_4fSSxHu_sw" key="documentation" value="Makes sense for DiagramLabels of Links only (now). Constants from {@link org.eclipse.draw2d.ConnectionLocator} are: MIDDLE = Alignment.CENTER, TARGET = Alignment.END, SOURCE = Alignment.BEGINNING"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUHTvn0_EeC_4fSSxHu_sw"
        name="alignment" eType="#_qUH6zn0_EeC_4fSSxHu_sw"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUHTwX0_EeC_4fSSxHu_sw" name="GradientFacet"
      eSuperTypes="#_qUHTsn0_EeC_4fSSxHu_sw">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUHTwn0_EeC_4fSSxHu_sw"
        name="direction" eType="#_qUH6mH0_EeC_4fSSxHu_sw"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUHTxX0_EeC_4fSSxHu_sw" name="LabelOffsetFacet"
      eSuperTypes="#_qUHTsn0_EeC_4fSSxHu_sw">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUHTxn0_EeC_4fSSxHu_sw"
        name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUHTyH0_EeC_4fSSxHu_sw"
        name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUHTy30_EeC_4fSSxHu_sw" name="FigureHandle"
      interface="true">
    <eAnnotations xmi:id="_qUHTzH0_EeC_4fSSxHu_sw" source="http://www.eclipse.org/emf/2002/GenModel">
      <details xmi:id="_qUHTzX0_EeC_4fSSxHu_sw" key="documentation" value="Entry in the figure's hierarchy to reference from diagram element"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_qUHTzn0_EeC_4fSSxHu_sw"
        name="referencingElements" upperBound="-1" eType="#_qUHTjH0_EeC_4fSSxHu_sw"
        eOpposite="#_qUHTl30_EeC_4fSSxHu_sw"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUHT0H0_EeC_4fSSxHu_sw" name="CustomClass"
      interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUHT0X0_EeC_4fSSxHu_sw"
        name="qualifiedClassName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUHT030_EeC_4fSSxHu_sw"
        name="bundleName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_qUHT1X0_EeC_4fSSxHu_sw"
        name="attributes" upperBound="-1" eType="#_qUHT130_EeC_4fSSxHu_sw" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUHT130_EeC_4fSSxHu_sw" name="CustomAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUHT2H0_EeC_4fSSxHu_sw"
        name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUHT2n0_EeC_4fSSxHu_sw"
        name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="null"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUHT3H0_EeC_4fSSxHu_sw"
        name="directAccess" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUHT3n0_EeC_4fSSxHu_sw"
        name="multiStatementValue" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUHT4H0_EeC_4fSSxHu_sw" name="FigureAccessor"
      eSuperTypes="#_qUHTy30_EeC_4fSSxHu_sw">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUHT4X0_EeC_4fSSxHu_sw"
        name="accessor" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_qUHT430_EeC_4fSSxHu_sw"
        name="typedFigure" eType="#_qUH7UX0_EeC_4fSSxHu_sw"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUHT5n0_EeC_4fSSxHu_sw" name="Color"
      interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUHT530_EeC_4fSSxHu_sw" name="RGBColor"
      eSuperTypes="#_qUHT5n0_EeC_4fSSxHu_sw">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUHT6H0_EeC_4fSSxHu_sw"
        name="red" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUHT6n0_EeC_4fSSxHu_sw"
        name="green" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUHT7H0_EeC_4fSSxHu_sw"
        name="blue" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUHT730_EeC_4fSSxHu_sw" name="ConstantColor"
      eSuperTypes="#_qUHT5n0_EeC_4fSSxHu_sw">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUHT8H0_EeC_4fSSxHu_sw"
        name="value" lowerBound="1" eType="#_qUHT830_EeC_4fSSxHu_sw"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" xmi:id="_qUHT830_EeC_4fSSxHu_sw" name="ColorConstants">
    <eLiterals xmi:id="_qUHT9H0_EeC_4fSSxHu_sw" name="white" literal="white"/>
    <eLiterals xmi:id="_qUHT9X0_EeC_4fSSxHu_sw" name="black" value="1" literal="black"/>
    <eLiterals xmi:id="_qUHT9n0_EeC_4fSSxHu_sw" name="lightGray" value="2" literal="lightGray"/>
    <eLiterals xmi:id="_qUHT930_EeC_4fSSxHu_sw" name="gray" value="3" literal="gray"/>
    <eLiterals xmi:id="_qUHT-H0_EeC_4fSSxHu_sw" name="darkGray" value="4" literal="darkGray"/>
    <eLiterals xmi:id="_qUHT-X0_EeC_4fSSxHu_sw" name="red" value="5" literal="red"/>
    <eLiterals xmi:id="_qUHT-n0_EeC_4fSSxHu_sw" name="orange" value="6" literal="orange"/>
    <eLiterals xmi:id="_qUHT-30_EeC_4fSSxHu_sw" name="yellow" value="7" literal="yellow"/>
    <eLiterals xmi:id="_qUHT_H0_EeC_4fSSxHu_sw" name="green" value="8" literal="green"/>
    <eLiterals xmi:id="_qUHT_X0_EeC_4fSSxHu_sw" name="lightGreen" value="9" literal="lightGreen"/>
    <eLiterals xmi:id="_qUHT_n0_EeC_4fSSxHu_sw" name="darkGreen" value="10" literal="darkGreen"/>
    <eLiterals xmi:id="_qUHT_30_EeC_4fSSxHu_sw" name="cyan" value="11" literal="cyan"/>
    <eLiterals xmi:id="_qUHUAH0_EeC_4fSSxHu_sw" name="lightBlue" value="12" literal="lightBlue"/>
    <eLiterals xmi:id="_qUHUAX0_EeC_4fSSxHu_sw" name="blue" value="13" literal="blue"/>
    <eLiterals xmi:id="_qUHUAn0_EeC_4fSSxHu_sw" name="darkBlue" value="14" literal="darkBlue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUHUA30_EeC_4fSSxHu_sw" name="Font"
      interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUHUBH0_EeC_4fSSxHu_sw" name="BasicFont"
      eSuperTypes="#_qUHUA30_EeC_4fSSxHu_sw">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUHUBX0_EeC_4fSSxHu_sw"
        name="faceName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUHUB30_EeC_4fSSxHu_sw"
        name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="9"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUHUCX0_EeC_4fSSxHu_sw"
        name="style" eType="#_qUHUDH0_EeC_4fSSxHu_sw" defaultValueLiteral="NORMAL"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" xmi:id="_qUHUDH0_EeC_4fSSxHu_sw" name="FontStyle">
    <eLiterals xmi:id="_qUHUDX0_EeC_4fSSxHu_sw" name="NORMAL" literal="NORMAL"/>
    <eLiterals xmi:id="_qUHUDn0_EeC_4fSSxHu_sw" name="BOLD" value="1" literal="BOLD"/>
    <eLiterals xmi:id="_qUHUD30_EeC_4fSSxHu_sw" name="ITALIC" value="2" literal="ITALIC"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUHUEH0_EeC_4fSSxHu_sw" name="Point">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUHUEX0_EeC_4fSSxHu_sw"
        name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUHUE30_EeC_4fSSxHu_sw"
        name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUHUFX0_EeC_4fSSxHu_sw" name="Dimension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUHUFn0_EeC_4fSSxHu_sw"
        name="dx" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUHUGH0_EeC_4fSSxHu_sw"
        name="dy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUHUGn0_EeC_4fSSxHu_sw" name="Insets">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUHUG30_EeC_4fSSxHu_sw"
        name="top" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUHUHX0_EeC_4fSSxHu_sw"
        name="left" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUH6gH0_EeC_4fSSxHu_sw"
        name="bottom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUH6gn0_EeC_4fSSxHu_sw"
        name="right" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUH6hH0_EeC_4fSSxHu_sw" name="Border"
      interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUH6hX0_EeC_4fSSxHu_sw" name="LineBorder"
      eSuperTypes="#_qUH6hH0_EeC_4fSSxHu_sw">
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_qUH6hn0_EeC_4fSSxHu_sw"
        name="color" eType="#_qUHT5n0_EeC_4fSSxHu_sw" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUH6iH0_EeC_4fSSxHu_sw"
        name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUH6i30_EeC_4fSSxHu_sw" name="MarginBorder"
      eSuperTypes="#_qUH6hH0_EeC_4fSSxHu_sw">
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_qUH6jH0_EeC_4fSSxHu_sw"
        name="insets" eType="#_qUHUGn0_EeC_4fSSxHu_sw" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUH6j30_EeC_4fSSxHu_sw" name="CompoundBorder"
      eSuperTypes="#_qUH6hH0_EeC_4fSSxHu_sw">
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_qUH6kH0_EeC_4fSSxHu_sw"
        name="outer" eType="#_qUH6hH0_EeC_4fSSxHu_sw" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_qUH6kn0_EeC_4fSSxHu_sw"
        name="inner" eType="#_qUH6hH0_EeC_4fSSxHu_sw" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUH6lX0_EeC_4fSSxHu_sw" name="CustomBorder"
      eSuperTypes="#_qUH6hH0_EeC_4fSSxHu_sw #_qUHT0H0_EeC_4fSSxHu_sw"/>
  <eClassifiers xsi:type="ecore:EEnum" xmi:id="_qUH6mH0_EeC_4fSSxHu_sw" name="Direction">
    <eAnnotations xmi:id="_qUH6mX0_EeC_4fSSxHu_sw" source="http://www.eclipse.org/emf/2002/GenModel">
      <details xmi:id="_qUH6mn0_EeC_4fSSxHu_sw" key="documentation" value="Geographical bit constants from org.eclipse.draw2d.PositionConstants"/>
    </eAnnotations>
    <eLiterals xmi:id="_qUH6m30_EeC_4fSSxHu_sw" name="NONE" literal="NONE"/>
    <eLiterals xmi:id="_qUH6nH0_EeC_4fSSxHu_sw" name="NORTH" value="1" literal="NORTH"/>
    <eLiterals xmi:id="_qUH6nX0_EeC_4fSSxHu_sw" name="SOUTH" value="4" literal="SOUTH"/>
    <eLiterals xmi:id="_qUH6nn0_EeC_4fSSxHu_sw" name="WEST" value="8" literal="WEST"/>
    <eLiterals xmi:id="_qUH6n30_EeC_4fSSxHu_sw" name="EAST" value="16" literal="EAST"/>
    <eLiterals xmi:id="_qUH6oH0_EeC_4fSSxHu_sw" name="NORTH_EAST" value="17" literal="NORTH_EAST"/>
    <eLiterals xmi:id="_qUH6oX0_EeC_4fSSxHu_sw" name="NORTH_WEST" value="9" literal="NORTH_WEST"/>
    <eLiterals xmi:id="_qUH6on0_EeC_4fSSxHu_sw" name="SOUTH_EAST" value="20" literal="SOUTH_EAST"/>
    <eLiterals xmi:id="_qUH6o30_EeC_4fSSxHu_sw" name="SOUTH_WEST" value="12" literal="SOUTH_WEST"/>
    <eLiterals xmi:id="_qUH6pH0_EeC_4fSSxHu_sw" name="NORTH_SOUTH" value="5" literal="NORTH_SOUTH"/>
    <eLiterals xmi:id="_qUH6pX0_EeC_4fSSxHu_sw" name="EAST_WEST" value="24" literal="EAST_WEST"/>
    <eLiterals xmi:id="_qUH6pn0_EeC_4fSSxHu_sw" name="NSEW" value="29" literal="NSEW"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" xmi:id="_qUH6p30_EeC_4fSSxHu_sw" name="LineKind">
    <eAnnotations xmi:id="_qUH6qH0_EeC_4fSSxHu_sw" source="http://www.eclipse.org/emf/2002/GenModel">
      <details xmi:id="_qUH6qX0_EeC_4fSSxHu_sw" key="documentation" value="org.eclipse.draw2d.Graphics.LINE_* (== org.eclipse.swt.SWT.LINE_*. Values are same as SWT constants"/>
    </eAnnotations>
    <eLiterals xmi:id="_qUH6qn0_EeC_4fSSxHu_sw" name="LINE_SOLID" value="1" literal="LINE_SOLID"/>
    <eLiterals xmi:id="_qUH6q30_EeC_4fSSxHu_sw" name="LINE_DASH" value="2" literal="LINE_DASH"/>
    <eLiterals xmi:id="_qUH6rH0_EeC_4fSSxHu_sw" name="LINE_DOT" value="3" literal="LINE_DOT"/>
    <eLiterals xmi:id="_qUH6rX0_EeC_4fSSxHu_sw" name="LINE_DASHDOT" value="4" literal="LINE_DASHDOT"/>
    <eLiterals xmi:id="_qUH6rn0_EeC_4fSSxHu_sw" name="LINE_DASHDOTDOT" value="5" literal="LINE_DASHDOTDOT"/>
    <eLiterals xmi:id="_qUH6r30_EeC_4fSSxHu_sw" name="LINE_CUSTOM" value="6" literal="LINE_CUSTOM"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUH6sH0_EeC_4fSSxHu_sw" name="LayoutData"
      interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_qUH6sX0_EeC_4fSSxHu_sw"
        name="owner" lowerBound="1" eType="#_qUH6030_EeC_4fSSxHu_sw" eOpposite="#_qUH61H0_EeC_4fSSxHu_sw"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUH6s30_EeC_4fSSxHu_sw" name="CustomLayoutData"
      eSuperTypes="#_qUH6sH0_EeC_4fSSxHu_sw #_qUHT0H0_EeC_4fSSxHu_sw"/>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUH6tn0_EeC_4fSSxHu_sw" name="GridLayoutData"
      eSuperTypes="#_qUH6sH0_EeC_4fSSxHu_sw">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUH6t30_EeC_4fSSxHu_sw"
        name="grabExcessHorizontalSpace" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUH6uX0_EeC_4fSSxHu_sw"
        name="grabExcessVerticalSpace" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUH6u30_EeC_4fSSxHu_sw"
        name="verticalSpan" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUH6vX0_EeC_4fSSxHu_sw"
        name="horizontalSpan" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUH6v30_EeC_4fSSxHu_sw"
        name="horizontalIndent" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_qUH6wX0_EeC_4fSSxHu_sw"
        name="sizeHint" eType="#_qUHUFX0_EeC_4fSSxHu_sw" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUH6w30_EeC_4fSSxHu_sw"
        name="verticalAlignment" lowerBound="1" eType="#_qUH6zn0_EeC_4fSSxHu_sw" defaultValueLiteral="CENTER"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUH6xX0_EeC_4fSSxHu_sw"
        name="horizontalAlignment" lowerBound="1" eType="#_qUH6zn0_EeC_4fSSxHu_sw"
        defaultValueLiteral="CENTER"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUH6yH0_EeC_4fSSxHu_sw" name="BorderLayoutData"
      eSuperTypes="#_qUH6sH0_EeC_4fSSxHu_sw">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUH6yX0_EeC_4fSSxHu_sw"
        name="vertical" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUH6y30_EeC_4fSSxHu_sw"
        name="alignment" lowerBound="1" eType="#_qUH6zn0_EeC_4fSSxHu_sw" defaultValueLiteral="CENTER"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" xmi:id="_qUH6zn0_EeC_4fSSxHu_sw" name="Alignment">
    <eLiterals xmi:id="_qUH6z30_EeC_4fSSxHu_sw" name="BEGINNING" literal="BEGINNING"/>
    <eLiterals xmi:id="_qUH60H0_EeC_4fSSxHu_sw" name="CENTER" value="1" literal="CENTER"/>
    <eLiterals xmi:id="_qUH60X0_EeC_4fSSxHu_sw" name="END" value="2" literal="END"/>
    <eLiterals xmi:id="_qUH60n0_EeC_4fSSxHu_sw" name="FILL" value="3" literal="FILL"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUH6030_EeC_4fSSxHu_sw" name="Layoutable"
      interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_qUH61H0_EeC_4fSSxHu_sw"
        name="layoutData" eType="#_qUH6sH0_EeC_4fSSxHu_sw" containment="true" eOpposite="#_qUH6sX0_EeC_4fSSxHu_sw"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_qUH61n0_EeC_4fSSxHu_sw"
        name="layout" eType="#_qUH7Yn0_EeC_4fSSxHu_sw" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUH62H0_EeC_4fSSxHu_sw" name="FigureMarker"
      interface="true" eSuperTypes="#_qUH6030_EeC_4fSSxHu_sw">
    <eAnnotations xmi:id="_qUH62X0_EeC_4fSSxHu_sw" source="http://www.eclipse.org/emf/2002/GenModel">
      <details xmi:id="_qUH62n0_EeC_4fSSxHu_sw" key="documentation" value="Anything you could combine visual representation from. Ordinary GEF figures, custom-defined or references to defined elsewhere."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_qUH6230_EeC_4fSSxHu_sw"
        name="parent" eType="#_qUH63n0_EeC_4fSSxHu_sw" changeable="false" resolveProxies="false"
        eOpposite="#_qUH64X0_EeC_4fSSxHu_sw"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUH63n0_EeC_4fSSxHu_sw" name="Figure"
      interface="true" eSuperTypes="#_qUH62H0_EeC_4fSSxHu_sw #_qUHTy30_EeC_4fSSxHu_sw #_qUHTcX0_EeC_4fSSxHu_sw">
    <eAnnotations xmi:id="_qUH6330_EeC_4fSSxHu_sw" source="http://www.eclipse.org/emf/2002/GenModel">
      <details xmi:id="_qUH64H0_EeC_4fSSxHu_sw" key="documentation" value="org.eclipse.draw2d.Figure"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_qUH64X0_EeC_4fSSxHu_sw"
        name="children" upperBound="-1" eType="#_qUH62H0_EeC_4fSSxHu_sw" containment="true"
        eOpposite="#_qUH6230_EeC_4fSSxHu_sw"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_qUH6430_EeC_4fSSxHu_sw"
        name="foregroundColor" eType="#_qUHT5n0_EeC_4fSSxHu_sw" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_qUH65X0_EeC_4fSSxHu_sw"
        name="backgroundColor" eType="#_qUHT5n0_EeC_4fSSxHu_sw" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_qUH6530_EeC_4fSSxHu_sw"
        name="maximumSize" eType="#_qUHUFX0_EeC_4fSSxHu_sw" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_qUH66X0_EeC_4fSSxHu_sw"
        name="minimumSize" eType="#_qUHUFX0_EeC_4fSSxHu_sw" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_qUH6630_EeC_4fSSxHu_sw"
        name="preferredSize" eType="#_qUHUFX0_EeC_4fSSxHu_sw" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_qUH67X0_EeC_4fSSxHu_sw"
        name="font" eType="#_qUHUA30_EeC_4fSSxHu_sw" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_qUH6730_EeC_4fSSxHu_sw"
        name="insets" eType="#_qUHUGn0_EeC_4fSSxHu_sw" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_qUH68X0_EeC_4fSSxHu_sw"
        name="border" eType="#_qUH6hH0_EeC_4fSSxHu_sw" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_qUH6830_EeC_4fSSxHu_sw"
        name="location" eType="#_qUHUEH0_EeC_4fSSxHu_sw" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_qUH69X0_EeC_4fSSxHu_sw"
        name="size" eType="#_qUHUEH0_EeC_4fSSxHu_sw" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUH6-n0_EeC_4fSSxHu_sw" name="FigureRef"
      eSuperTypes="#_qUH62H0_EeC_4fSSxHu_sw">
    <eAnnotations xmi:id="_qUH6-30_EeC_4fSSxHu_sw" source="http://www.eclipse.org/emf/2002/GenModel">
      <details xmi:id="_qUH6_H0_EeC_4fSSxHu_sw" key="documentation" value="Need this to facilitate reuse of figures while keeping (so nice looking) containment relationship in the Figure class"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_qUH6_X0_EeC_4fSSxHu_sw"
        name="figure" lowerBound="1" eType="#_qUH63n0_EeC_4fSSxHu_sw">
      <eAnnotations xmi:id="_qUH6_n0_EeC_4fSSxHu_sw" source="http://www.eclipse.org/emf/2002/GenModel">
        <details xmi:id="_qUH6_30_EeC_4fSSxHu_sw" key="documentation" value="not FigureMarker because don't want to reference figure references."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUH7An0_EeC_4fSSxHu_sw" name="ConnectionFigure"
      interface="true" eSuperTypes="#_qUH63n0_EeC_4fSSxHu_sw"/>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUH7BH0_EeC_4fSSxHu_sw" name="DecorationFigure"
      interface="true" eSuperTypes="#_qUH63n0_EeC_4fSSxHu_sw"/>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUH7Bn0_EeC_4fSSxHu_sw" name="Shape"
      abstract="true" eSuperTypes="#_qUH63n0_EeC_4fSSxHu_sw">
    <eAnnotations xmi:id="_qUH7B30_EeC_4fSSxHu_sw" source="http://www.eclipse.org/emf/2002/GenModel">
      <details xmi:id="_qUH7CH0_EeC_4fSSxHu_sw" key="documentation" value="org.eclipse.draw2d.Shape"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUH7CX0_EeC_4fSSxHu_sw"
        name="outline" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUH7C30_EeC_4fSSxHu_sw"
        name="fill" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUH7DX0_EeC_4fSSxHu_sw"
        name="lineWidth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUH7D30_EeC_4fSSxHu_sw"
        name="lineKind" eType="#_qUH6p30_EeC_4fSSxHu_sw"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUH7EX0_EeC_4fSSxHu_sw"
        name="xorFill" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUH7E30_EeC_4fSSxHu_sw"
        name="xorOutline" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_qUH7FX0_EeC_4fSSxHu_sw"
        name="resolvedChildren" upperBound="-1" eType="#_qUH63n0_EeC_4fSSxHu_sw" changeable="false"
        volatile="true" transient="true" derived="true">
      <eAnnotations xmi:id="_qUH7Fn0_EeC_4fSSxHu_sw" source="http://www.eclipse.org/emf/2002/GenModel">
        <details xmi:id="_qUH7F30_EeC_4fSSxHu_sw" key="documentation" value="Same as children, but resolves child FigureRefs, if any, to Figures"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUH7Gn0_EeC_4fSSxHu_sw" name="Label"
      eSuperTypes="#_qUH63n0_EeC_4fSSxHu_sw">
    <eAnnotations xmi:id="_qUH7G30_EeC_4fSSxHu_sw" source="http://www.eclipse.org/emf/2002/GenModel">
      <details xmi:id="_qUH7HH0_EeC_4fSSxHu_sw" key="documentation" value="org.eclipse.draw2d.Label"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUH7HX0_EeC_4fSSxHu_sw"
        name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUH7IH0_EeC_4fSSxHu_sw" name="LabeledContainer"
      eSuperTypes="#_qUH63n0_EeC_4fSSxHu_sw">
    <eAnnotations xmi:id="_qUH7IX0_EeC_4fSSxHu_sw" source="http://www.eclipse.org/emf/2002/GenModel">
      <details xmi:id="_qUH7In0_EeC_4fSSxHu_sw" key="documentation" value="org.eclipse.draw2d.LabeledContainer"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUH7JH0_EeC_4fSSxHu_sw" name="Rectangle"
      eSuperTypes="#_qUH7Bn0_EeC_4fSSxHu_sw">
    <eAnnotations xmi:id="_qUH7JX0_EeC_4fSSxHu_sw" source="http://www.eclipse.org/emf/2002/GenModel">
      <details xmi:id="_qUH7Jn0_EeC_4fSSxHu_sw" key="documentation" value="org.eclipse.draw2d.RectangleFigure"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUH7KH0_EeC_4fSSxHu_sw" name="RoundedRectangle"
      eSuperTypes="#_qUH7Bn0_EeC_4fSSxHu_sw">
    <eAnnotations xmi:id="_qUH7KX0_EeC_4fSSxHu_sw" source="http://www.eclipse.org/emf/2002/GenModel">
      <details xmi:id="_qUH7Kn0_EeC_4fSSxHu_sw" key="documentation" value="org.eclipse.draw2d.RoundedRectangle"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUH7K30_EeC_4fSSxHu_sw"
        name="cornerWidth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="8"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUH7LX0_EeC_4fSSxHu_sw"
        name="cornerHeight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="8"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUH7MH0_EeC_4fSSxHu_sw" name="Ellipse"
      eSuperTypes="#_qUH7Bn0_EeC_4fSSxHu_sw">
    <eAnnotations xmi:id="_qUH7MX0_EeC_4fSSxHu_sw" source="http://www.eclipse.org/emf/2002/GenModel">
      <details xmi:id="_qUH7Mn0_EeC_4fSSxHu_sw" key="documentation" value="org.eclipse.draw2d.Ellipse"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUH7NH0_EeC_4fSSxHu_sw" name="Polyline"
      eSuperTypes="#_qUH7Bn0_EeC_4fSSxHu_sw">
    <eAnnotations xmi:id="_qUH7NX0_EeC_4fSSxHu_sw" source="http://www.eclipse.org/emf/2002/GenModel">
      <details xmi:id="_qUH7Nn0_EeC_4fSSxHu_sw" key="documentation" value="org.eclipse.draw2d.Polyline"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_qUH7N30_EeC_4fSSxHu_sw"
        name="template" upperBound="-1" eType="#_qUHUEH0_EeC_4fSSxHu_sw" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUH7On0_EeC_4fSSxHu_sw" name="Polygon"
      eSuperTypes="#_qUH7NH0_EeC_4fSSxHu_sw">
    <eAnnotations xmi:id="_qUH7O30_EeC_4fSSxHu_sw" source="http://www.eclipse.org/emf/2002/GenModel">
      <details xmi:id="_qUH7PH0_EeC_4fSSxHu_sw" key="documentation" value="org.eclipse.draw2d.Polygon"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUH7Pn0_EeC_4fSSxHu_sw" name="PolylineConnection"
      eSuperTypes="#_qUH7NH0_EeC_4fSSxHu_sw #_qUH7An0_EeC_4fSSxHu_sw">
    <eAnnotations xmi:id="_qUH7P30_EeC_4fSSxHu_sw" source="http://www.eclipse.org/emf/2002/GenModel">
      <details xmi:id="_qUH7QH0_EeC_4fSSxHu_sw" key="documentation" value="org.eclipse.draw2d.PolylineConnection"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_qUH7QX0_EeC_4fSSxHu_sw"
        name="sourceDecoration" eType="#_qUH7BH0_EeC_4fSSxHu_sw"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_qUH7Q30_EeC_4fSSxHu_sw"
        name="targetDecoration" eType="#_qUH7BH0_EeC_4fSSxHu_sw"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUH7R30_EeC_4fSSxHu_sw" name="PolylineDecoration"
      eSuperTypes="#_qUH7NH0_EeC_4fSSxHu_sw #_qUH7BH0_EeC_4fSSxHu_sw">
    <eAnnotations xmi:id="_qUH7SH0_EeC_4fSSxHu_sw" source="http://www.eclipse.org/emf/2002/GenModel">
      <details xmi:id="_qUH7SX0_EeC_4fSSxHu_sw" key="documentation" value="org.eclipse.draw2d.PolylineDecoration"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUH7TH0_EeC_4fSSxHu_sw" name="PolygonDecoration"
      eSuperTypes="#_qUH7On0_EeC_4fSSxHu_sw #_qUH7BH0_EeC_4fSSxHu_sw">
    <eAnnotations xmi:id="_qUH7TX0_EeC_4fSSxHu_sw" source="http://www.eclipse.org/emf/2002/GenModel">
      <details xmi:id="_qUH7Tn0_EeC_4fSSxHu_sw" key="documentation" value="org.eclipse.draw2d.PolygonDecoration"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUH7UX0_EeC_4fSSxHu_sw" name="CustomFigure"
      eSuperTypes="#_qUH63n0_EeC_4fSSxHu_sw #_qUHT0H0_EeC_4fSSxHu_sw">
    <eAnnotations xmi:id="_qUH7Un0_EeC_4fSSxHu_sw" source="http://www.eclipse.org/emf/2002/GenModel">
      <details xmi:id="_qUH7U30_EeC_4fSSxHu_sw" key="documentation" value="Any figure class provided by some bundle"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_qUH7VH0_EeC_4fSSxHu_sw"
        name="customChildren" upperBound="-1" eType="#_qUHT4H0_EeC_4fSSxHu_sw" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUH7WH0_EeC_4fSSxHu_sw" name="CustomDecoration"
      eSuperTypes="#_qUH7UX0_EeC_4fSSxHu_sw #_qUH7BH0_EeC_4fSSxHu_sw">
    <eAnnotations xmi:id="_qUH7WX0_EeC_4fSSxHu_sw" source="http://www.eclipse.org/emf/2002/GenModel">
      <details xmi:id="_qUH7Wn0_EeC_4fSSxHu_sw" key="documentation" value="Same as CustomFigure, but for Decorations"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUH7XX0_EeC_4fSSxHu_sw" name="CustomConnection"
      eSuperTypes="#_qUH7UX0_EeC_4fSSxHu_sw #_qUH7An0_EeC_4fSSxHu_sw">
    <eAnnotations xmi:id="_qUH7Xn0_EeC_4fSSxHu_sw" source="http://www.eclipse.org/emf/2002/GenModel">
      <details xmi:id="_qUH7X30_EeC_4fSSxHu_sw" key="documentation" value="Same as CustomFigure, but for Connections"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUH7Yn0_EeC_4fSSxHu_sw" name="Layout"
      interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUH7Y30_EeC_4fSSxHu_sw" name="CustomLayout"
      eSuperTypes="#_qUH7Yn0_EeC_4fSSxHu_sw #_qUHT0H0_EeC_4fSSxHu_sw"/>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUH7Zn0_EeC_4fSSxHu_sw" name="GridLayout"
      eSuperTypes="#_qUH7Yn0_EeC_4fSSxHu_sw">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUH7Z30_EeC_4fSSxHu_sw"
        name="numColumns" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUH7aX0_EeC_4fSSxHu_sw"
        name="equalWidth" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_qUH7a30_EeC_4fSSxHu_sw"
        name="margins" eType="#_qUHUFX0_EeC_4fSSxHu_sw" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_qUH7bX0_EeC_4fSSxHu_sw"
        name="spacing" eType="#_qUHUFX0_EeC_4fSSxHu_sw" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUH7cH0_EeC_4fSSxHu_sw" name="BorderLayout"
      eSuperTypes="#_qUH7Yn0_EeC_4fSSxHu_sw">
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_qUH7cX0_EeC_4fSSxHu_sw"
        name="spacing" eType="#_qUHUFX0_EeC_4fSSxHu_sw" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUH7dH0_EeC_4fSSxHu_sw" name="FlowLayout"
      eSuperTypes="#_qUH7Yn0_EeC_4fSSxHu_sw">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUH7dX0_EeC_4fSSxHu_sw"
        name="vertical" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUH7d30_EeC_4fSSxHu_sw"
        name="matchMinorSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUH7eX0_EeC_4fSSxHu_sw"
        name="forceSingleLine" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUH7e30_EeC_4fSSxHu_sw"
        name="majorAlignment" eType="#_qUH6zn0_EeC_4fSSxHu_sw" defaultValueLiteral="BEGINNING"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUH7fX0_EeC_4fSSxHu_sw"
        name="minorAlignment" eType="#_qUH6zn0_EeC_4fSSxHu_sw" defaultValueLiteral="BEGINNING"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUH7f30_EeC_4fSSxHu_sw"
        name="majorSpacing" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="5"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_qUH7gX0_EeC_4fSSxHu_sw"
        name="minorSpacing" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUH7hH0_EeC_4fSSxHu_sw" name="XYLayout"
      eSuperTypes="#_qUH7Yn0_EeC_4fSSxHu_sw"/>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUH7hn0_EeC_4fSSxHu_sw" name="XYLayoutData"
      eSuperTypes="#_qUH6sH0_EeC_4fSSxHu_sw">
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_qUH7h30_EeC_4fSSxHu_sw"
        name="topLeft" lowerBound="1" eType="#_qUHUEH0_EeC_4fSSxHu_sw" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_qUH7iX0_EeC_4fSSxHu_sw"
        name="size" lowerBound="1" eType="#_qUHUFX0_EeC_4fSSxHu_sw" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUH7jH0_EeC_4fSSxHu_sw" name="StackLayout"
      eSuperTypes="#_qUH7Yn0_EeC_4fSSxHu_sw"/>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_qUKWwH0_EeC_4fSSxHu_sw" name="ScalablePolygon"
      eSuperTypes="#_qUH7On0_EeC_4fSSxHu_sw">
    <eAnnotations xmi:id="_qUKWwX0_EeC_4fSSxHu_sw" source="http://www.eclipse.org/emf/2002/GenModel">
      <details xmi:id="_qUKWwn0_EeC_4fSSxHu_sw" key="documentation" value="Marker interface to denote polygons with ability to autoscale to fit all available bounds. Separate class is needed instead of property in the Polygon class because of generalization PolygonDecoration extends Polygon"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
