/*
 * generated by Xtext 2.9.1
 */
package org.eclipse.emf.refactor.examples.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SimpleWebModelingLanguageAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/eclipse/emf/refactor/examples/parser/antlr/internal/InternalSimpleWebModelingLanguage.tokens");
	}
}
