<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="hypertextlayer" nsURI="http://hypertextlayer/1.0" nsPrefix="hypertextlayer">
  <eClassifiers xsi:type="ecore:EClass" name="HypertextLayer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pages" upperBound="-1"
        eType="#//Page" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="startPage" eType="#//StaticPage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataLayer" eType="ecore:EClass ../../org.sidiff.coevolution.example.swml.crossreferences.datalayer/model/DataLayer.ecore#//DataLayer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Page" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="-1"
        eType="#//Link" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DynamicPage" abstract="true" eSuperTypes="#//Page">
    <eStructuralFeatures xsi:type="ecore:EReference" name="shows" eType="ecore:EClass ../../org.sidiff.coevolution.example.swml.crossreferences.datalayer/model/DataLayer.ecore#//Entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StaticPage" eSuperTypes="#//Page"/>
  <eClassifiers xsi:type="ecore:EClass" name="IndexPage" eSuperTypes="#//DynamicPage"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataPage" eSuperTypes="#//DynamicPage"/>
  <eClassifiers xsi:type="ecore:EClass" name="Link">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//Page"/>
  </eClassifiers>
</ecore:EPackage>
