/**
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package org.eclipse.emf.refactor.examples.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.emf.refactor.examples.SimpleWebModelingLanguageRuntimeModule;
import org.eclipse.emf.refactor.examples.SimpleWebModelingLanguageStandaloneSetup;
import org.eclipse.emf.refactor.examples.ide.SimpleWebModelingLanguageIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class SimpleWebModelingLanguageIdeSetup extends SimpleWebModelingLanguageStandaloneSetup {
  @Override
  public Injector createInjector() {
    SimpleWebModelingLanguageRuntimeModule _simpleWebModelingLanguageRuntimeModule = new SimpleWebModelingLanguageRuntimeModule();
    SimpleWebModelingLanguageIdeModule _simpleWebModelingLanguageIdeModule = new SimpleWebModelingLanguageIdeModule();
    return Guice.createInjector(Modules2.mixin(_simpleWebModelingLanguageRuntimeModule, _simpleWebModelingLanguageIdeModule));
  }
}
