/**
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package org.eclipse.emf.refactor.examples.ide;

import org.eclipse.emf.refactor.examples.ide.AbstractSimpleWebModelingLanguageIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class SimpleWebModelingLanguageIdeModule extends AbstractSimpleWebModelingLanguageIdeModule {
}
