/*
 * generated by Xtext 2.9.1
 */
package org.eclipse.emf.refactor.examples.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSimpleWebModelingLanguageScopeProvider extends DelegatingScopeProvider {
}
