/**
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package org.eclipse.emf.refactor.examples.simpleWebModelingLanguage.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.refactor.examples.simpleWebModelingLanguage.SimpleWebModelingLanguagePackage;
import org.eclipse.emf.refactor.examples.simpleWebModelingLanguage.StaticPage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Static Page</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class StaticPageImpl extends PageImpl implements StaticPage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StaticPageImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SimpleWebModelingLanguagePackage.Literals.STATIC_PAGE;
  }

} //StaticPageImpl
