/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.emf.refactor.examples.simpleWebModelingLanguage.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.eclipse.emf.refactor.examples.simpleWebModelingLanguage.HypertextLayer;
import org.eclipse.emf.refactor.examples.simpleWebModelingLanguage.Page;
import org.eclipse.emf.refactor.examples.simpleWebModelingLanguage.SimpleWebModelingLanguagePackage;
import org.eclipse.emf.refactor.examples.simpleWebModelingLanguage.StaticPage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Hypertext Layer</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.emf.refactor.examples.simpleWebModelingLanguage.impl.HypertextLayerImpl#getPages <em>Pages</em>}</li>
 *   <li>{@link org.eclipse.emf.refactor.examples.simpleWebModelingLanguage.impl.HypertextLayerImpl#getStartPage <em>Start Page</em>}</li>
 * </ul>
 *
 * @generated
 */
public class HypertextLayerImpl extends MinimalEObjectImpl.Container implements HypertextLayer
{
  /**
   * The cached value of the '{@link #getPages() <em>Pages</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPages()
   * @generated
   * @ordered
   */
  protected EList<Page> pages;

  /**
   * The cached value of the '{@link #getStartPage() <em>Start Page</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStartPage()
   * @generated
   * @ordered
   */
  protected StaticPage startPage;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected HypertextLayerImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SimpleWebModelingLanguagePackage.Literals.HYPERTEXT_LAYER;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Page> getPages()
  {
    if (pages == null)
    {
      pages = new EObjectContainmentEList<Page>(Page.class, this, SimpleWebModelingLanguagePackage.HYPERTEXT_LAYER__PAGES);
    }
    return pages;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public StaticPage getStartPage()
  {
    if (startPage != null && startPage.eIsProxy())
    {
      InternalEObject oldStartPage = (InternalEObject)startPage;
      startPage = (StaticPage)eResolveProxy(oldStartPage);
      if (startPage != oldStartPage)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, SimpleWebModelingLanguagePackage.HYPERTEXT_LAYER__START_PAGE, oldStartPage, startPage));
      }
    }
    return startPage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public StaticPage basicGetStartPage()
  {
    return startPage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setStartPage(StaticPage newStartPage)
  {
    StaticPage oldStartPage = startPage;
    startPage = newStartPage;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SimpleWebModelingLanguagePackage.HYPERTEXT_LAYER__START_PAGE, oldStartPage, startPage));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SimpleWebModelingLanguagePackage.HYPERTEXT_LAYER__PAGES:
        return ((InternalEList<?>)getPages()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SimpleWebModelingLanguagePackage.HYPERTEXT_LAYER__PAGES:
        return getPages();
      case SimpleWebModelingLanguagePackage.HYPERTEXT_LAYER__START_PAGE:
        if (resolve) return getStartPage();
        return basicGetStartPage();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SimpleWebModelingLanguagePackage.HYPERTEXT_LAYER__PAGES:
        getPages().clear();
        getPages().addAll((Collection<? extends Page>)newValue);
        return;
      case SimpleWebModelingLanguagePackage.HYPERTEXT_LAYER__START_PAGE:
        setStartPage((StaticPage)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SimpleWebModelingLanguagePackage.HYPERTEXT_LAYER__PAGES:
        getPages().clear();
        return;
      case SimpleWebModelingLanguagePackage.HYPERTEXT_LAYER__START_PAGE:
        setStartPage((StaticPage)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SimpleWebModelingLanguagePackage.HYPERTEXT_LAYER__PAGES:
        return pages != null && !pages.isEmpty();
      case SimpleWebModelingLanguagePackage.HYPERTEXT_LAYER__START_PAGE:
        return startPage != null;
    }
    return super.eIsSet(featureID);
  }

} //HypertextLayerImpl
