<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http://model/1.0" nsPrefix="model">
  <eSubpackages name="EPackage0">
    <eClassifiers xsi:type="ecore:EClass" name="EClass0">
      <eOperations name="EOperation0">
        <eParameters name="p1"/>
      </eOperations>
      <eOperations name="EOperation1">
        <eParameters name="p2"/>
        <eParameters name="p3"/>
        <eParameters name="p4"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="EAttribute0" defaultValueLiteral=""/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="EAttribute1"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="EAttribute2"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="EAttribute3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EClass1">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="EAttribute4"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="EAttribute5"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="EPackage1">
    <eClassifiers xsi:type="ecore:EClass" name="EClass2">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="EAttribute6"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EClass3">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="EAttribute7" defaultValueLiteral=""/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="EAttribute8"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="EAttribute9"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="EAttribute10"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EClass4">
      <eOperations name="EOperation2"/>
      <eOperations name="EOperation3">
        <eParameters name="p5"/>
        <eParameters name="p6"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="EAttribute11"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="EAttribute12"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="EPackage2">
    <eClassifiers xsi:type="ecore:EClass" name="EClass5">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="EAttribute13"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="EAttribute14"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="EAttribute15"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EClass6">
      <eOperations name="EOperation4"/>
      <eOperations name="EOperation5">
        <eParameters name="p7"/>
        <eParameters name="p8"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="EAttribute16"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
