<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="asymmetric" nsURI="http://www.sidiff.org/difference/asymmetric/1.0"
    nsPrefix="asymmetric">
  <eClassifiers xsi:type="ecore:EClass" name="AsymmetricDifference">
    <eOperations name="initializeRuleBase"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operationInvocations" upperBound="-1"
        eType="#//OperationInvocation" containment="true" eOpposite="#//OperationInvocation/asymmetricDifference"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="originModel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EResource"
        changeable="false" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changedModel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EResource"
        changeable="false" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="depContainers" upperBound="-1"
        eType="#//DependencyContainer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterMappings" upperBound="-1"
        eType="#//ParameterMapping" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="executions" upperBound="-1"
        eType="#//Execution" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="symmetricDifference" eType="ecore:EClass ../../org.sidiff.difference.symmetric/model/Symmetric.ecore#//SymmetricDifference"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uriOriginModel" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uriChangedModel" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rulebase" eType="ecore:EClass ../../org.sidiff.editrule.rulebase/model/RuleBase.ecore#//RuleBase"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationInvocation" eSuperTypes="#//Execution">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="editRuleName" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="apply" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterBindings" upperBound="-1"
        eType="#//ParameterBinding" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" upperBound="-1"
        eType="#//DependencyContainer" eOpposite="#//DependencyContainer/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" upperBound="-1"
        eType="#//DependencyContainer" eOpposite="#//DependencyContainer/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="changeSet" eType="ecore:EClass ../../org.sidiff.difference.symmetric/model/Symmetric.ecore#//SemanticChangeSet"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="asymmetricDifference" eType="#//AsymmetricDifference"
        eOpposite="#//AsymmetricDifference/operationInvocations"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterBinding" abstract="true">
    <eOperations name="isDefaultValue" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="formalName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectParameterBinding" eSuperTypes="#//ParameterBinding">
    <eOperations name="isMappingTarget" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actualA" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actualB" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" upperBound="-1"
        eType="#//ParameterMapping" eOpposite="#//ParameterMapping/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" eType="#//ParameterMapping"
        eOpposite="#//ParameterMapping/target"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueParameterBinding" eSuperTypes="#//ParameterBinding">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actual" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DependencyContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//OperationInvocation" eOpposite="#//OperationInvocation/outgoing"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//OperationInvocation" eOpposite="#//OperationInvocation/incoming"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependencies" upperBound="-1"
        eType="#//Dependency" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterMapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//ObjectParameterBinding" eOpposite="#//ObjectParameterBinding/outgoing"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//ObjectParameterBinding" eOpposite="#//ObjectParameterBinding/incoming"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DependencyKind">
    <eLiterals name="UseDelete"/>
    <eLiterals name="CreateUse" value="1"/>
    <eLiterals name="DeleteForbid" value="2"/>
    <eLiterals name="ForbidCreate" value="3"/>
    <eLiterals name="ChangeUse" value="4"/>
    <eLiterals name="UseChange" value="5"/>
    <eLiterals name="ChangeForbid" value="6"/>
    <eLiterals name="ForbidChange" value="7"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParallelExecution" eSuperTypes="#//Execution">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subExecutions" upperBound="-1"
        eType="#//Execution"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SequentialExecution" eSuperTypes="#//Execution">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subExecutions" upperBound="-1"
        eType="#//Execution"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Execution" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="MultiParameterBinding" eSuperTypes="#//ParameterBinding">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterBindings" upperBound="-1"
        eType="#//ParameterBinding" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeDependency" eSuperTypes="#//Dependency">
    <eStructuralFeatures xsi:type="ecore:EReference" name="object" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EdgeDependency" eSuperTypes="#//Dependency">
    <eStructuralFeatures xsi:type="ecore:EReference" name="srcObject" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tgtObject" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeDependency" eSuperTypes="#//Dependency">
    <eStructuralFeatures xsi:type="ecore:EReference" name="object" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EAttribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dependency" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//DependencyKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//OperationInvocation" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//OperationInvocation" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
</ecore:EPackage>
