/**
 *
 * $Id$
 */
package org.sidiff.magicdraw.statecharts.effective.model.MagicDrawStatechartsEffective.validation;

import org.eclipse.emf.common.util.EList;

import org.sidiff.magicdraw.statecharts.effective.model.MagicDrawStatechartsEffective.Behavior;
import org.sidiff.magicdraw.statecharts.effective.model.MagicDrawStatechartsEffective.Constraint;

/**
 * A sample validator interface for {@link org.sidiff.magicdraw.statecharts.effective.model.MagicDrawStatechartsEffective.Behavior}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BehaviorValidator {
	boolean validate();

	boolean validateIsReentrant(boolean value);
	boolean validatePostcondition(EList<Constraint> value);
	boolean validatePrecondition(EList<Constraint> value);
	boolean validateRedefinedBehavior(EList<Behavior> value);
}
