/**
 *
 * $Id$
 */
package org.sidiff.magicdraw.statecharts.effective.model.MagicDrawStatechartsEffective.validation;

import org.eclipse.emf.common.util.EList;

import org.sidiff.magicdraw.statecharts.effective.model.MagicDrawStatechartsEffective.Pseudostate;
import org.sidiff.magicdraw.statecharts.effective.model.MagicDrawStatechartsEffective.State;

/**
 * A sample validator interface for {@link org.sidiff.magicdraw.statecharts.effective.model.MagicDrawStatechartsEffective.ConnectionPointReference}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConnectionPointReferenceValidator {
	boolean validate();

	boolean validateEntry(EList<Pseudostate> value);
	boolean validateExit(EList<Pseudostate> value);
	boolean validateState(State value);
}
