/**
 *
 * $Id$
 */
package org.sidiff.magicdraw.statecharts.effective.model.MagicDrawStatechartsEffective.validation;

import org.sidiff.magicdraw.statecharts.effective.model.MagicDrawStatechartsEffective.PseudostateKind;
import org.sidiff.magicdraw.statecharts.effective.model.MagicDrawStatechartsEffective.State;
import org.sidiff.magicdraw.statecharts.effective.model.MagicDrawStatechartsEffective.StateMachine;

/**
 * A sample validator interface for {@link org.sidiff.magicdraw.statecharts.effective.model.MagicDrawStatechartsEffective.Pseudostate}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PseudostateValidator {
	boolean validate();

	boolean validateState(State value);
	boolean validateKind(PseudostateKind value);
	boolean validateStateMachine(StateMachine value);
}
